/**
 * The topic-wise timetable for the test series.
 *
 * Transcribed from the schedule PDF -- eighty-four days from the first paper to
 * the exam, each naming its Professional Knowledge topic and the Quant,
 * Reasoning and English item that sits beside it. It is a plan, not state:
 * nothing here is read from or written to the database, and no paper in the
 * `tests` table is linked to a row of it. A student reads it to know what is
 * coming; an admin reads it to know what to set.
 *
 * Which is why it lives as a module rather than a table. The plan changes when
 * somebody decides it should, in a commit, with the change visible in a diff --
 * not through a screen nobody would open twice. If it ever needs editing in the
 * product, that is a migration and a repo away, and this shape is what it would
 * carry.
 *
 * The dates were checked against a 2026 calendar: day 1 is Monday 28 September
 * 2026 and each day is the one after the last, so `date` and `label` agree for
 * all eighty-four. `tests/schedule.test.ts` re-checks that on every run.
 */

/** One of the three non-PK subjects on a day, and the note the plan adds to it. */
export type ScheduleSubject = {
  item: string
  /** A theme or a qualifier -- "Theme: banking and economy". */
  note?: string
}

export type ScheduleDay = {
  /** 1..84, counting from the first paper. */
  day: number
  /** ISO, IST. The day this sits on. */
  date: string
  /** How the plan writes that date: "Mon 28 Sep". */
  label: string
  /** The syllabus slot, where there is one: "OS 1", "DBMS 3". */
  code?: string
  /** What the day is: a topic name, "Week 3 Test 1", "Review 2", "EXAM". */
  test: string
  /** "Pattern A · 55 Q · 45 min", or what stands in its place on a review day. */
  pattern?: string
  pk: {
    topic?: string
    /** Where it sits in its subject: "Operating Systems 1 of 4". */
    source?: string
    /** The sub-topics under the topic, in the plan's own smaller print. */
    detail?: string
    /**
     * What a day that is not one topic is made of: a weekly test's question
     * blueprint, a full mock's subject counts, what a review day is for.
     *
     * Kept in reading order rather than split by weight. The plan alternates a
     * bold count with a normal-weight subject -- "DBMS 5" "(Transactions)"
     * "CN 5" "(Transport)" -- and partitioning those by how they are set would
     * hand back two lists with no way to pair them up again.
     */
    plan?: string
  }
  /**
   * Absent on a day that has no separate QRE column -- a second weekly test, a
   * review day, the exam. The table spans the PK cell across the three.
   */
  quant?: ScheduleSubject
  reasoning?: ScheduleSubject
  english?: ScheduleSubject
}

export type ScheduleSection = {
  /** "Week 1", "Phase 2". */
  name: string
  /** The subjects it covers. Absent on a phase, which is not about subjects. */
  subjects?: string
  from: number
  to: number
  /** The span as the plan writes it: "28 Sep - 04 Oct". */
  dates: string
  days: ScheduleDay[]
}

export const SCHEDULE_TITLE = 'RRB SO IT Scale II — PK + QRE test schedule'

export const SCHEDULE: ScheduleSection[] = [
  {
    name: "Week 1",
    subjects: "Operating Systems, Computer Networks",
    from: 1, to: 7, dates: "28 Sep - 04 Oct",
    days: [
    { day: 1, date: "2026-09-28", label: "Mon 28 Sep", code: "OS 1", test: "Processes, Threads and CPU Scheduling", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "Processes, Threads and CPU Scheduling", source: "Operating Systems 1 of 4", detail: "OS types, process states, PCB, system calls, context switching, user vs kernel threads, fork() output; FCFS, SJF, SRTF, RR, priority, MLFQ with waiting/turnaround numericals" }, quant: { item: "Simplification (BODMAS, fractions, surds and indices)" }, reasoning: { item: "Linear Seating - single row, same facing" }, english: { item: "RC - Factual and Detail questions", note: "Theme: banking and economy" } },
    { day: 2, date: "2026-09-29", label: "Tue 29 Sep", code: "OS 2", test: "Synchronization and Deadlock", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "Synchronization and Deadlock", source: "Operating Systems 2 of 4", detail: "critical section, Peterson's solution, semaphores, mutex, monitors, producer-consumer, readers-writers, dining philosophers; deadlock conditions, RAG, Banker's algorithm, detection and recovery" }, quant: { item: "Percentage (base change, successive %)" }, reasoning: { item: "Direct Inequality" }, english: { item: "Error Detection - subject-verb agreement, tenses" } },
    { day: 3, date: "2026-09-30", label: "Wed 30 Sep", code: "OS 3", test: "Memory Management and Virtual Memory", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "Memory Management and Virtual Memory", source: "Operating Systems 3 of 4", detail: "paging, segmentation, page-table size and multi-level paging numericals, TLB and EMAT, fragmentation, demand paging, FIFO/LRU/OPT, Belady's anomaly, thrashing" }, quant: { item: "Approximation" }, reasoning: { item: "Syllogism - basic + possibility" }, english: { item: "Single Fillers (vocabulary)" } },
    { day: 4, date: "2026-10-01", label: "Thu 01 Oct", code: "OS 4", test: "File Systems, Disk, I/O and Linux", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "File Systems, Disk, I/O and Linux", source: "Operating Systems 4 of 4", detail: "file allocation methods, directory structures, disk scheduling (FCFS, SSTF, SCAN, C-SCAN, LOOK) numericals, RAID levels, Linux commands and permissions" }, quant: { item: "Table DI" }, reasoning: { item: "Floor Puzzle" }, english: { item: "Para Jumbles - 5 sentences" } },
    { day: 5, date: "2026-10-02", label: "Fri 02 Oct", code: "CN 1", test: "Models, Devices and Physical Layer", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "Models, Devices and Physical Layer", source: "Computer Networks 1 of 5", detail: "OSI and TCP/IP layers, hub/switch/router/gateway, topologies, transmission media, circuit vs packet switching, delay and throughput numericals" }, quant: { item: "Quadratic Equations (x vs y)" }, reasoning: { item: "Order and Ranking (positions, ranks)" }, english: { item: "Word Usage and Word Swap" } },
    { day: 6, date: "2026-10-03", label: "Sat 03 Oct", test: "Week 1 Test 1", pattern: "Pattern B · 160 Q · 120 min", pk: { plan: "Processes & Scheduling ×8 · Sync & Deadlock ×8 · Memory & VM ×8 · Files, Disk & Linux ×8 · Models & Devices ×8" }, quant: { item: "Simplification ×8 · Percentage ×8 · Approximation ×7 · Table DI ×10 · Quadratic Eq. ×7" }, reasoning: { item: "Linear (same facing) ×10 · Direct Inequality ×7 · Syllogism (basic) ×7 · Floor Puzzle ×10 · Order & Ranking ×6" }, english: { item: "RC Factual ×10 · ED: SVA & Tenses ×7 · Single Fillers ×7 · Para Jumbles (5) ×10 · Word Usage/Swap ×6" } },
    { day: 7, date: "2026-10-04", label: "Sun 04 Oct", test: "Week 1 Test 2", pattern: "Pattern B · 160 Q · 120 min", pk: { plan: "Same blueprint as Test 1 (Day 6). Fresh questions, zero reuse from Test 1 or the weekday tests." } },
    ],
  },
  {
    name: "Week 2",
    subjects: "Computer Networks, DBMS",
    from: 8, to: 14, dates: "05 Oct - 11 Oct",
    days: [
    { day: 8, date: "2026-10-05", label: "Mon 05 Oct", code: "CN 2", test: "Data Link Layer", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "Data Link Layer", source: "Computer Networks 2 of 5", detail: "framing, parity, CRC, checksum, Hamming code, stop-and-wait, Go-Back-N, Selective Repeat and efficiency numericals, ALOHA, CSMA/CD, Ethernet" }, quant: { item: "Ratio and Proportion" }, reasoning: { item: "Circular Seating - facing centre" }, english: { item: "RC - Inference questions", note: "Theme: technology and cybersecurity" } },
    { day: 9, date: "2026-10-06", label: "Tue 06 Oct", code: "CN 3", test: "Network Layer and IP Addressing", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "Network Layer and IP Addressing", source: "Computer Networks 3 of 5", detail: "IPv4 classes, subnetting, CIDR and supernetting numericals, IPv6 basics, routing (DV, LS, RIP, OSPF, BGP), NAT, ARP, ICMP" }, quant: { item: "Bar Graph DI" }, reasoning: { item: "Blood Relations - verbal" }, english: { item: "Error Detection - articles, prepositions, conjunctions" } },
    { day: 10, date: "2026-10-07", label: "Wed 07 Oct", code: "CN 4", test: "Transport Layer", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "Transport Layer", source: "Computer Networks 4 of 5", detail: "TCP vs UDP, 3-way handshake and teardown, sequence numbers, sliding window, congestion control (slow start, Tahoe, Reno), ports and sockets" }, quant: { item: "Number Series - missing term" }, reasoning: { item: "Box Puzzle (single stack)" }, english: { item: "Cloze Test - grammar-based" } },
    { day: 11, date: "2026-10-08", label: "Thu 08 Oct", code: "CN 5", test: "Application Layer Protocols", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "Application Layer Protocols", source: "Computer Networks 5 of 5", detail: "DNS, HTTP/HTTPS basics, SMTP/POP3/IMAP, FTP, DHCP, SNMP, Telnet/SSH, well-known ports [firewalls, VPN and TLS live in Security 3]" }, quant: { item: "Averages" }, reasoning: { item: "Coded Inequality" }, english: { item: "Sentence Parts Rearrangement (A-E)" } },
    { day: 12, date: "2026-10-09", label: "Fri 09 Oct", code: "DBMS 1", test: "ER Model, Keys and Constraints", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "ER Model, Keys and Constraints", source: "DBMS 1 of 5", detail: "entity/attribute types, cardinality, participation, weak entities, ER-to-relational mapping, super/candidate/primary/alternate/foreign keys, integrity constraints" }, quant: { item: "Line Graph DI" }, reasoning: { item: "Direction Sense - point-based" }, english: { item: "Sentence Connectors" } },
    { day: 13, date: "2026-10-10", label: "Sat 10 Oct", test: "Week 2 Test 1", pattern: "Pattern B · 160 Q · 120 min", pk: { plan: "Data Link ×8 · IP & Routing ×8 · Transport ×8 · App Protocols ×8 · ER & Keys ×8" }, quant: { item: "Ratio & Proportion ×7 · Bar DI ×10 · Series (missing) ×7 · Averages ×6 · Line DI ×10" }, reasoning: { item: "Circular (centre) ×10 · Blood Rel. (verbal) ×7 · Box Puzzle ×10 · Coded Inequality ×7 · Direction (point) ×6" }, english: { item: "RC Inference ×10 · ED: Articles/Preps ×7 · Cloze (grammar) ×10 · Sentence Parts Rearr. ×7 · Connectors ×6" } },
    { day: 14, date: "2026-10-11", label: "Sun 11 Oct", test: "Week 2 Test 2", pattern: "Pattern B · 160 Q · 120 min", pk: { plan: "Same blueprint as Test 1 (Day 13). Fresh questions, zero reuse from Test 1 or the weekday tests." } },
    ],
  },
  {
    name: "Week 3",
    subjects: "DBMS, Data Structures & Algorithms",
    from: 15, to: 21, dates: "12 Oct - 18 Oct",
    days: [
    { day: 15, date: "2026-10-12", label: "Mon 12 Oct", code: "DBMS 2", test: "SQL and Relational Algebra", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "SQL and Relational Algebra", source: "DBMS 2 of 5", detail: "DDL/DML/DCL/TCL, joins (inner/outer/self), GROUP BY/HAVING, subqueries, NULL semantics, views, relational algebra operators and query output" }, quant: { item: "Profit and Loss" }, reasoning: { item: "Linear Seating - single row, mixed facing" }, english: { item: "RC - Main Idea and Title", note: "Theme: environment and agriculture" } },
    { day: 16, date: "2026-10-13", label: "Tue 13 Oct", code: "DBMS 3", test: "Functional Dependencies and Normalization", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "Functional Dependencies and Normalization", source: "DBMS 3 of 5", detail: "FDs, attribute closure, candidate-key finding, minimal cover, 1NF-2NF-3NF-BCNF-4NF, lossless and dependency-preserving decomposition" }, quant: { item: "Pie Chart DI" }, reasoning: { item: "Coding-Decoding - letter/number shifting" }, english: { item: "Phrase Replacement and Sentence Improvement" } },
    { day: 17, date: "2026-10-14", label: "Wed 14 Oct", code: "DBMS 4", test: "Transactions and Concurrency Control", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "Transactions and Concurrency Control", source: "DBMS 4 of 5", detail: "ACID, schedules, conflict and view serializability, precedence graphs, recoverable/cascadeless schedules, 2PL variants, timestamp ordering, deadlock handling" }, quant: { item: "Number Series - wrong term" }, reasoning: { item: "Month-Date Scheduling Puzzle" }, english: { item: "Double Fillers" } },
    { day: 18, date: "2026-10-15", label: "Thu 15 Oct", code: "DBMS 5", test: "Indexing, Storage, Recovery and NoSQL", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "Indexing, Storage, Recovery and NoSQL", source: "DBMS 5 of 5", detail: "file organization, primary/secondary/clustered indexes, B-tree and B+ tree order and height numericals, extendible hashing for files, log-based recovery, checkpoints, NoSQL types" }, quant: { item: "Simple Interest" }, reasoning: { item: "Syllogism - 'only a few' and reverse" }, english: { item: "Para Jumbles - fixed/starter sentence" } },
    { day: 19, date: "2026-10-16", label: "Fri 16 Oct", code: "DSA 1", test: "Arrays, Linked Lists, Stacks and Queues", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "Arrays, Linked Lists, Stacks and Queues", source: "Data Structures & Algorithms 1 of 4", detail: "array address calculation, singly/doubly/circular linked lists, stacks (infix to postfix, evaluation), queues (circular, deque, priority queue)" }, quant: { item: "Compound Interest and Instalments" }, reasoning: { item: "Alphanumeric and Symbol Series" }, english: { item: "Idioms and Phrasal Verbs" } },
    { day: 20, date: "2026-10-17", label: "Sat 17 Oct", test: "Week 3 Test 1", pattern: "Pattern B · 160 Q · 120 min", pk: { plan: "SQL & RA ×8 · Normalization ×8 · Transactions ×8 · Indexing & Recovery ×8 · Linear DS ×8" }, quant: { item: "Profit & Loss ×8 · Pie DI ×10 · Series (wrong) ×8 · Simple Interest ×7 · CI & Instalments ×7" }, reasoning: { item: "Linear (mixed facing) ×10 · Coding (shifting) ×7 · Month-Date Puzzle ×10 · Syllogism (only a few) ×7 · Alphanumeric Series ×6" }, english: { item: "RC Main Idea ×10 · Phrase Replacement ×7 · Double Fillers ×7 · Para Jumbles (fixed) ×10 · Idioms/Phrasal ×6" } },
    { day: 21, date: "2026-10-18", label: "Sun 18 Oct", test: "Week 3 Test 2", pattern: "Pattern B · 160 Q · 120 min", pk: { plan: "Same blueprint as Test 1 (Day 20). Fresh questions, zero reuse from Test 1 or the weekday tests." } },
    ],
  },
  {
    name: "Week 4",
    subjects: "Data Structures & Algorithms, Cyber Security & Cryptography",
    from: 22, to: 28, dates: "19 Oct - 25 Oct",
    days: [
    { day: 22, date: "2026-10-19", label: "Mon 19 Oct", code: "DSA 2", test: "Trees, Heaps and Hashing", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "Trees, Heaps and Hashing", source: "Data Structures & Algorithms 2 of 4", detail: "binary tree properties and counting, traversals and reconstruction, BST, AVL rotations, heaps and heapify; hash functions, probing, chaining, load factor [B-trees live in DBMS 5]" }, quant: { item: "Time and Work" }, reasoning: { item: "Circular Seating - mixed facing" }, english: { item: "RC - Vocabulary in Context", note: "Theme: science and health" } },
    { day: 23, date: "2026-10-20", label: "Tue 20 Oct", code: "DSA 3", test: "Graphs, Sorting and Searching", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "Graphs, Sorting and Searching", source: "Data Structures & Algorithms 3 of 4", detail: "graph representations, BFS, DFS, topological sort, connected components; bubble, selection, insertion, merge, quick, heap, counting sort (complexity, stability, passes); linear and binary search" }, quant: { item: "Caselet DI (paragraph data)" }, reasoning: { item: "Floor-Flat Puzzle" }, english: { item: "Error Detection - pronouns, modifiers, parallelism" } },
    { day: 24, date: "2026-10-21", label: "Wed 21 Oct", code: "DSA 4", test: "Complexity and Algorithm Design", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "Complexity and Algorithm Design", source: "Data Structures & Algorithms 4 of 4", detail: "asymptotic notation, recurrences and Master theorem, greedy (Huffman, Kruskal, Prim, Dijkstra), dynamic programming (knapsack, LCS, matrix chain), divide and conquer" }, quant: { item: "Quantity Comparison (Q1 vs Q2)" }, reasoning: { item: "Coding-Decoding - sentence/word coding" }, english: { item: "Cloze Test - vocabulary-based" } },
    { day: 25, date: "2026-10-22", label: "Thu 22 Oct", code: "Sec 1", test: "Security Fundamentals and Malware", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "Security Fundamentals and Malware", source: "Cyber Security & Cryptography 1 of 5", detail: "CIA triad, AAA, threat vs vulnerability vs risk, security policies, virus, worm, trojan, ransomware, rootkit, spyware, botnet" }, quant: { item: "Speed, Time and Distance" }, reasoning: { item: "Parallel-row Seating" }, english: { item: "Odd Sentence Out and Paragraph Completion" } },
    { day: 26, date: "2026-10-23", label: "Fri 23 Oct", code: "Sec 2", test: "Cryptography", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "Cryptography", source: "Cyber Security & Cryptography 2 of 5", detail: "DES, 3DES, AES, block cipher modes, RSA, Diffie-Hellman, ECC with small-number numericals, MD5/SHA, MACs, digital signatures, PKI and certificates" }, quant: { item: "Problems on Ages" }, reasoning: { item: "Blood Relations - coded" }, english: { item: "Misspelt Words (spelling errors in a sentence)" } },
    { day: 27, date: "2026-10-24", label: "Sat 24 Oct", test: "Week 4 Test 1", pattern: "Pattern B · 160 Q · 120 min", pk: { plan: "Trees & Hashing ×8 · Graphs & Sorting ×8 · Algorithm Design ×8 · Fundamentals & Malware ×8 · Cryptography ×8" }, quant: { item: "Time & Work ×8 · Caselet DI ×10 · Quantity Comparison ×8 · Speed-Time-Distance ×7 · Ages ×7" }, reasoning: { item: "Circular (mixed) ×10 · Floor-Flat Puzzle ×10 · Coding (sentence) ×5 · Parallel-row ×10 · Blood Rel. (coded) ×5" }, english: { item: "RC Vocab-in-context ×10 · ED: Pronouns/Modifiers ×7 · Cloze (vocab) ×10 · Odd Sentence/Para Compl. ×7 · Misspelt Words ×6" } },
    { day: 28, date: "2026-10-25", label: "Sun 25 Oct", test: "Week 4 Test 2", pattern: "Pattern B · 160 Q · 120 min", pk: { plan: "Same blueprint as Test 1 (Day 27). Fresh questions, zero reuse from Test 1 or the weekday tests." } },
    ],
  },
  {
    name: "Week 5",
    subjects: "Cyber Security & Cryptography, C",
    from: 29, to: 35, dates: "26 Oct - 01 Nov",
    days: [
    { day: 29, date: "2026-10-26", label: "Mon 26 Oct", code: "Sec 3", test: "Network Security", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "Network Security", source: "Cyber Security & Cryptography 3 of 5", detail: "packet filter, stateful, application gateway, NGFW; IDS vs IPS; VPN and IPsec; SSL/TLS handshake; DMZ; proxy; WEP, WPA2, WPA3" }, quant: { item: "Pipes and Cisterns" }, reasoning: { item: "Day-of-week Scheduling Puzzle" }, english: { item: "RC - Tone, Attitude and Author's Purpose", note: "Theme: editorial and opinion" } },
    { day: 30, date: "2026-10-27", label: "Tue 27 Oct", code: "Sec 4", test: "Attacks and Application Security", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "Attacks and Application Security", source: "Cyber Security & Cryptography 4 of 5", detail: "phishing and social engineering, DoS/DDoS, MITM, spoofing, SQL injection, XSS, CSRF, buffer overflow, password attacks, OWASP Top 10" }, quant: { item: "Missing-value Table DI" }, reasoning: { item: "Direction Sense - coded and shadow" }, english: { item: "Error Detection - nouns, quantifiers, adjectives and adverbs" } },
    { day: 31, date: "2026-10-28", label: "Wed 28 Oct", code: "Sec 5", test: "Security Management and Banking Context", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "Security Management and Banking Context", source: "Cyber Security & Cryptography 5 of 5", detail: "DAC, MAC, RBAC; MFA, OTP, biometrics; ISO 27001; IT Act 2000; CERT-In; RBI cyber security framework; BCP and DR" }, quant: { item: "Trains" }, reasoning: { item: "Square/Rectangular Seating" }, english: { item: "Fixed Fillers (a given word: which sentence can it complete)" } },
    { day: 32, date: "2026-10-29", label: "Thu 29 Oct", code: "C 1", test: "C Fundamentals and Compilation", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "C Fundamentals and Compilation", source: "C 1 of 2", detail: "data types and ranges, operators and precedence, type conversion, control flow and loops, printf/scanf formats, output prediction; preprocess-compile-link, compiler vs interpreter, phases of a compiler" }, quant: { item: "Mixture and Alligation" }, reasoning: { item: "Input-Output (machine)" }, english: { item: "Word Rearrangement (jumbled words into a sentence)" } },
    { day: 33, date: "2026-10-30", label: "Fri 30 Oct", code: "C 2", test: "C Pointers, Arrays, Strings and Functions", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "C Pointers, Arrays, Strings and Functions", source: "C 2 of 2", detail: "pointer arithmetic, pointers to pointers, arrays and strings, functions and recursion, call by value vs reference, storage classes, structures and unions, malloc/calloc/free, output questions" }, quant: { item: "Data Sufficiency (Quant)" }, reasoning: { item: "Alphabet and Word Test" }, english: { item: "Commonly Confused Words (homophones, affect/effect type pairs)" } },
    { day: 34, date: "2026-10-31", label: "Sat 31 Oct", test: "Week 5 Test 1", pattern: "Pattern B · 160 Q · 120 min", pk: { plan: "Network Security ×8 · Attacks & AppSec ×8 · Sec. Mgmt & Banking ×8 · C Basics ×8 · C Pointers & Functions ×8" }, quant: { item: "Pipes & Cisterns ×8 · Missing-value DI ×10 · Trains ×8 · Mixture & Alligation ×7 · Data Sufficiency ×7" }, reasoning: { item: "Day Scheduling ×10 · Direction (coded) ×5 · Square/Rect Seating ×10 · Input-Output ×10 · Alphabet & Word ×5" }, english: { item: "RC Tone & Purpose ×10 · ED: Nouns/Quantifiers ×8 · Fixed Fillers ×8 · Word Rearrangement ×7 · Confused Words ×7" } },
    { day: 35, date: "2026-11-01", label: "Sun 01 Nov", test: "Week 5 Test 2", pattern: "Pattern B · 160 Q · 120 min", pk: { topic: "IBPS SO Mains is today (IBPS calendar).", plan: "Same blueprint as Test 1 (Day 34). Fresh questions, zero reuse. If you are sitting it, skip this test: Test 2 is the designated flex slot." } },
    ],
  },
  {
    name: "Week 6",
    subjects: "C++ and OOP, Java, Python",
    from: 36, to: 42, dates: "02 Nov - 08 Nov",
    days: [
    { day: 36, date: "2026-11-02", label: "Mon 02 Nov", code: "C++ 1", test: "OOP Concepts through C++", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "OOP Concepts through C++", source: "C++ and OOP 1 of 2", detail: "classes and objects, encapsulation, inheritance types and the diamond problem, abstraction, access specifiers, constructors (default, parameterized, copy), destructors, this pointer, static members [language-neutral OOP theory lives here]" }, quant: { item: "Boats and Streams" }, reasoning: { item: "Year/Age-based Puzzle" }, english: { item: "RC - Short Passages (paragraph inference)", note: "Theme: rural credit and RRBs" } },
    { day: 37, date: "2026-11-03", label: "Tue 03 Nov", code: "C++ 2", test: "C++ Polymorphism, Templates, STL and Exceptions", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "C++ Polymorphism, Templates, STL and Exceptions", source: "C++ and OOP 2 of 2", detail: "function and operator overloading, virtual and pure virtual functions, abstract classes, vtable idea, friend functions, templates, STL containers and iterators, exception handling, new/delete, references vs pointers" }, quant: { item: "Bar + Line Combined DI" }, reasoning: { item: "Data Sufficiency (Reasoning)" }, english: { item: "Correct Sentence Identification (which sentence is error-free)" } },
    { day: 38, date: "2026-11-04", label: "Wed 04 Nov", code: "Java 1", test: "Java Platform, Syntax and OOP in Java", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "Java Platform, Syntax and OOP in Java", source: "Java 1 of 2", detail: "JDK/JRE/JVM, bytecode, data types and wrapper classes, String immutability and String pool, StringBuilder, interfaces vs abstract classes, access modifiers, static and final, overloading/overriding rules, output questions" }, quant: { item: "Partnership" }, reasoning: { item: "Designation/Hierarchy Puzzle" }, english: { item: "Triple Fillers" } },
    { day: 39, date: "2026-11-05", label: "Thu 05 Nov", code: "Java 2", test: "Java Exceptions, Collections and Multithreading", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "Java Exceptions, Collections and Multithreading", source: "Java 2 of 2", detail: "checked vs unchecked exceptions, try-catch-finally, throw/throws; List, Set, Map, HashMap vs Hashtable, ArrayList vs LinkedList; Thread vs Runnable, lifecycle, synchronized; garbage collection; JDBC basics" }, quant: { item: "Discount and Marked Price" }, reasoning: { item: "Statement and Assumption" }, english: { item: "Column-based Sentence Formation" } },
    { day: 40, date: "2026-11-06", label: "Fri 06 Nov", code: "Python 1", test: "Python Basics and Output Questions", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "Python Basics and Output Questions", source: "Python 1 of 3", detail: "dynamic typing, data types, operators (//, %, **), mutability, strings and slicing, control flow, range, print formatting, indentation rules, output prediction" }, quant: { item: "Number Series - new pattern (series-based questions)" }, reasoning: { item: "Comparison Puzzle (heights, weights, marks)" }, english: { item: "Collocations (natural word partnerships)" } },
    { day: 41, date: "2026-11-07", label: "Sat 07 Nov", test: "Week 6 Test 1", pattern: "Pattern B · 160 Q · 120 min", pk: { plan: "OOP in C++ ×8 · C++ Advanced ×8 · Java Core ×8 · Java Advanced ×8 · Python Basics ×8" }, quant: { item: "Boats & Streams ×8 · Bar+Line DI ×10 · Partnership ×8 · Discount & MP ×7 · Series (new pattern) ×7" }, reasoning: { item: "Year/Age Puzzle ×10 · Data Sufficiency ×5 · Designation Puzzle ×10 · Assumption ×5 · Comparison Puzzle ×10" }, english: { item: "RC Short Passages ×10 · Correct Sentence ×8 · Triple Fillers ×8 · Column-based ×7 · Collocations ×7" } },
    { day: 42, date: "2026-11-08", label: "Sun 08 Nov", test: "Week 6 Test 2", pattern: "Pattern B · 160 Q · 120 min", pk: { plan: "Same blueprint as Test 1 (Day 41). Fresh questions, zero reuse from Test 1 or the weekday tests." } },
    ],
  },
  {
    name: "Week 7",
    subjects: "Python, Computer Organization & Digital Logic, Software Engineering",
    from: 43, to: 49, dates: "09 Nov - 15 Nov",
    days: [
    { day: 43, date: "2026-11-09", label: "Mon 09 Nov", code: "Python 2", test: "Python Data Structures and Functions", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "Python Data Structures and Functions", source: "Python 2 of 3", detail: "list/tuple/set/dict methods and costs, comprehensions, default and keyword arguments, *args/**kwargs, lambda, map/filter, LEGB scope, recursion, generators" }, quant: { item: "Mensuration 2D" }, reasoning: { item: "Uncertain-number Puzzle" }, english: { item: "RC - Statement Evaluation (which of I, II, III is true)", note: "Theme: labour markets and skilling" } },
    { day: 44, date: "2026-11-10", label: "Tue 10 Nov", code: "Python 3", test: "Python OOP, Exceptions, Files and Libraries", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "Python OOP, Exceptions, Files and Libraries", source: "Python 3 of 3", detail: "classes, __init__ and self, inheritance, dunder methods, try/except/finally, file handling, modules and packages, NumPy and Pandas basics" }, quant: { item: "Pie + Table Combined DI" }, reasoning: { item: "Statement and Conclusion" }, english: { item: "Error Detection - inversion, comparison, redundancy" } },
    { day: 45, date: "2026-11-11", label: "Wed 11 Nov", code: "COA 1", test: "Number Systems and Digital Logic", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "Number Systems and Digital Logic", source: "Computer Organization & Digital Logic 1 of 2", detail: "conversions, 1's and 2's complement, IEEE 754, Boolean algebra, K-maps, universal gates, MUX/decoder/adders, flip-flops, counters, shift registers" }, quant: { item: "Permutation and Combination" }, reasoning: { item: "Box Puzzle - multi-attribute (weights, colours)" }, english: { item: "Common-word Fillers (one word fits every blank)" } },
    { day: 46, date: "2026-11-12", label: "Thu 12 Nov", code: "COA 2", test: "CPU, Memory Hierarchy, Cache and Pipelining", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "CPU, Memory Hierarchy, Cache and Pipelining", source: "Computer Organization & Digital Logic 2 of 2", detail: "instruction formats and addressing modes, RISC vs CISC, control unit types; cache mapping and tag/index/offset numericals, AMAT; RAM/ROM; pipeline speedup and hazards; interrupts, DMA, buses" }, quant: { item: "Mensuration 3D" }, reasoning: { item: "Course of Action" }, english: { item: "Sentence Starters and Sentence Combining" } },
    { day: 47, date: "2026-11-13", label: "Fri 13 Nov", code: "SE 1", test: "SDLC Models, Agile, Requirements and Design", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "SDLC Models, Agile, Requirements and Design", source: "Software Engineering 1 of 2", detail: "waterfall, V, incremental, spiral, prototype, RAD; Agile, Scrum, Kanban; DevOps and CI/CD; feasibility, SRS, functional vs non-functional requirements; UML and DFD; cohesion and coupling" }, quant: { item: "Probability" }, reasoning: { item: "Number-based Reasoning (3-digit numbers)" }, english: { item: "Synonyms and Antonyms (standalone) †" } },
    { day: 48, date: "2026-11-14", label: "Sat 14 Nov", test: "Week 7 Test 1", pattern: "Pattern B · 160 Q · 120 min", pk: { plan: "Py Data Structures ×8 · Py OOP & Libraries ×8 · Digital Logic ×8 · CPU, Cache & Pipeline ×8 · SDLC & Design ×8" }, quant: { item: "Mensuration 2D ×8 · Pie+Table DI ×10 · P&C ×8 · Mensuration 3D ×7 · Probability ×7" }, reasoning: { item: "Uncertain-number ×10 · Conclusion ×7 · Box (multi-attr) ×10 · Course of Action ×7 · Number-based ×6" }, english: { item: "RC Statement Eval. ×10 · ED: Inversion/Comparison ×8 · Common-word Fillers ×8 · Starters/Combining ×7 · Synonyms/Antonyms † ×7" } },
    { day: 49, date: "2026-11-15", label: "Sun 15 Nov", test: "Week 7 Test 2", pattern: "Pattern B · 160 Q · 120 min", pk: { plan: "Same blueprint as Test 1 (Day 48). Fresh questions, zero reuse from Test 1 or the weekday tests." } },
    ],
  },
  {
    name: "Week 8",
    subjects: "Software Engineering, AI/ML and Data, Web Technologies",
    from: 50, to: 56, dates: "16 Nov - 22 Nov",
    days: [
    { day: 50, date: "2026-11-16", label: "Mon 16 Nov", code: "SE 2", test: "Software Testing, Estimation and Quality", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "Software Testing, Estimation and Quality", source: "Software Engineering 2 of 2", detail: "test levels, BVA, equivalence partitioning, decision tables, statement/branch/path coverage, cyclomatic complexity, regression, alpha/beta, V&V; LOC, function points, COCOMO numericals; risk; maintenance types; CMMI, ISO 9001; version control" }, quant: { item: "Stacked Bar DI" }, reasoning: { item: "Double-attribute Mixed Puzzle" }, english: { item: "RC - Critical Reading (author's argument and assumptions)", note: "Theme: digital public infrastructure" } },
    { day: 51, date: "2026-11-17", label: "Tue 17 Nov", code: "AI/Data 1", test: "AI and Machine Learning Basics", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "AI and Machine Learning Basics", source: "AI/ML and Data 1 of 2", detail: "AI vs ML vs DL; supervised, unsupervised, reinforcement; regression, classification, clustering; decision trees, k-NN, k-means, SVM, naive Bayes; overfitting; confusion matrix, precision, recall, F1; neural network and LLM basics; AI in banking (fraud detection, chatbots)" }, quant: { item: "Number System (HCF/LCM, remainders, divisibility)" }, reasoning: { item: "Strengthen and Weaken Arguments" }, english: { item: "Error Detection - conditionals, modals, subjunctive" } },
    { day: 52, date: "2026-11-18", label: "Wed 18 Nov", code: "AI/Data 2", test: "Data Warehousing, Mining, Big Data and BI", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "Data Warehousing, Mining, Big Data and BI", source: "AI/ML and Data 2 of 2", detail: "OLTP vs OLAP, star and snowflake schemas, fact and dimension tables, ETL, data marts, OLAP operations; Apriori support and confidence; Big Data Vs, Hadoop, HDFS, MapReduce, Spark; BI dashboards (Power BI)" }, quant: { item: "Arithmetic-based DI (work, speed or interest data)" }, reasoning: { item: "Linear Seating - distance-based" }, english: { item: "Cloze Test - error-based (replace the incorrect bold word)" } },
    { day: 53, date: "2026-11-19", label: "Thu 19 Nov", code: "Web 1", test: "HTML5 and CSS", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "HTML5 and CSS", source: "Web Technologies 1 of 2", detail: "document structure, tags, forms and input types, tables, semantic elements, attributes; CSS selectors, specificity, box model, positioning, flexbox and grid, responsive basics" }, quant: { item: "Linear Equations and Problems on Numbers" }, reasoning: { item: "Cause and Effect, Inference" }, english: { item: "Para Jumbles - 6 sentences (position questions)" } },
    { day: 54, date: "2026-11-20", label: "Fri 20 Nov", code: "Web 2", test: "JavaScript, JSON/XML, HTTP and REST", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "JavaScript, JSON/XML, HTTP and REST", source: "Web Technologies 2 of 2", detail: "JavaScript types, var/let/const, functions, DOM and events; JSON vs XML; HTTP methods and status codes, cookies vs sessions, REST APIs, AJAX; client-server model and web servers" }, quant: { item: "Radar DI †" }, reasoning: { item: "Family-tree Puzzle (blood-relation based)" }, english: { item: "One-word Substitution †" } },
    { day: 55, date: "2026-11-21", label: "Sat 21 Nov", test: "Week 8 Test 1", pattern: "Pattern B · 160 Q · 120 min", pk: { plan: "Testing & Estimation ×8 · AI/ML Basics ×8 · DW, Mining & BI ×8 · HTML & CSS ×8 · JS, HTTP & REST ×8" }, quant: { item: "Stacked Bar DI ×10 · Number System ×5 · Arithmetic DI ×10 · Linear Equations ×5 · Radar DI † ×10" }, reasoning: { item: "Double-attribute ×10 · Strengthen/Weaken ×5 · Linear (distance) ×10 · Cause-Effect/Inference ×5 · Family-tree Puzzle ×10" }, english: { item: "RC Critical Reading ×10 · ED: Conditionals/Modals ×5 · Cloze (error-based) ×10 · Para Jumbles (6) ×10 · One-word Subst. † ×5" } },
    { day: 56, date: "2026-11-22", label: "Sun 22 Nov", test: "Week 8 Test 2", pattern: "Pattern B · 160 Q · 120 min", pk: { plan: "Same blueprint as Test 1 (Day 55). Fresh questions, zero reuse from Test 1 or the weekday tests." } },
    ],
  },
  {
    name: "Week 9",
    subjects: "Cloud Computing, Blockchain, Web3 and IoT, IT in Banking",
    from: 57, to: 63, dates: "23 Nov - 29 Nov",
    days: [
    { day: 57, date: "2026-11-23", label: "Mon 23 Nov", code: "Cloud 1", test: "Cloud Service and Deployment Models", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "Cloud Service and Deployment Models", source: "Cloud Computing 1 of 2", detail: "NIST characteristics, IaaS/PaaS/SaaS with examples, public/private/hybrid/community clouds, shared responsibility model, elasticity vs scalability, SLAs, pricing models" }, quant: { item: "Arithmetic Caselet (word-problem sets)" }, reasoning: { item: "Seating - unknown number of persons" }, english: { item: "RC - Long Passage (mixed question types)", note: "Theme: international trade and policy" } },
    { day: 58, date: "2026-11-24", label: "Tue 24 Nov", code: "Cloud 2", test: "Virtualization, Containers and Serverless", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "Virtualization, Containers and Serverless", source: "Cloud Computing 2 of 2", detail: "virtualization types, Type 1 vs Type 2 hypervisors, VMs vs containers, Docker and Kubernetes basics, serverless/FaaS, cloud storage types, cloud security basics" }, quant: { item: "Growth-rate DI (% change, back-calculation)" }, reasoning: { item: "Coding-Decoding - new pattern (conditional/number coding)" }, english: { item: "Highlighted-word Errors (which bold word is wrong or misplaced)" } },
    { day: 59, date: "2026-11-25", label: "Wed 25 Nov", code: "Web3 1", test: "Blockchain, Web3 and IoT", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "Blockchain, Web3 and IoT", source: "Blockchain, Web3 and IoT 1 of 1", detail: "blocks, hashing and Merkle trees, consensus (PoW, PoS), public vs permissioned chains, smart contracts, DApps, wallets and keys, tokens/NFTs, DeFi, CBDC (e-rupee), Web 1.0 vs 2.0 vs 3.0; IoT layers, MQTT/CoAP, edge and fog computing" }, quant: { item: "Double Pie DI" }, reasoning: { item: "Direction-based Puzzle (multi-person grid)" }, english: { item: "Sentence Completion (clause or phrase options)" } },
    { day: 60, date: "2026-11-26", label: "Thu 26 Nov", code: "Bank IT 1", test: "IT in Banking and Payment Systems", pattern: "Pattern A · 55 Q · 45 min", pk: { topic: "IT in Banking and Payment Systems", source: "IT in Banking 1 of 1", detail: "core banking solutions, NEFT, RTGS, IMPS, UPI, AePS, BBPS, NACH, CTS, SWIFT; ATM and card networks (RuPay, EMV chip), mobile and internet banking, API banking [BCP/DR lives in Security 5]" }, quant: { item: "Races and Circular Tracks †" }, reasoning: { item: "Miscellaneous (pair formation, odd one out, word formation)" }, english: { item: "Paragraph Summary (best summary of a paragraph)" } },
    { day: 61, date: "2026-11-27", label: "Fri 27 Nov", test: "Buffer / catch-up day", pattern: "No new topics", pk: { plan: "1) Finish any missed weekday tests from Weeks 1-9. 2) Then any missed Test 1s. 3) If nothing is pending: re-attempt your logged wrong answers from Weeks 7-9 weekend tests. No new questions, so the one-weekday rule is untouched." } },
    { day: 62, date: "2026-11-28", label: "Sat 28 Nov", test: "Week 9 Test 1", pattern: "Pattern B · 160 Q · 120 min", pk: { plan: "Cloud Models ×10 · Virtualization ×10 · Blockchain/Web3/IoT ×10 · Banking IT ×10" }, quant: { item: "Arithmetic Caselet ×10 · Growth-rate DI ×10 · Double Pie DI ×10 · Races & Circular † ×10" }, reasoning: { item: "Unknown-number Seating ×10 · Coding (new pattern) ×10 · Direction Puzzle ×10 · Miscellaneous ×10" }, english: { item: "RC Long Passage ×10 · Bold-word Errors ×10 · Sentence Completion ×10 · Paragraph Summary ×10" } },
    { day: 63, date: "2026-11-29", label: "Sun 29 Nov", test: "Week 9 Test 2", pattern: "Pattern B · 160 Q · 120 min", pk: { plan: "Same blueprint as Test 1 (Day 62). Fresh questions, zero reuse from Test 1 or the weekday tests." } },
    ],
  },
  {
    name: "Phase 2",
    subjects: "Full mocks and review",
    from: 64, to: 84, dates: "30 Nov - 20 Dec 2026",
    days: [
    { day: 64, date: "2026-11-30", label: "Mon 30 Nov", test: "Full Mock 01", pattern: "Pattern B · 160 Q · 120 min", pk: { plan: "DBMS 5 (ER & Keys) · CN 5 (Models & Devices) · Sec 5 (Fundamentals & Malware) · DSA 4 (Linear DS) · OS 4 (Processes & Scheduling) · Python 3 (Python Basics) · Java 2 (Java Core) · C 2 (C Basics) · C++ 2 (OOP in C++) · SE 2 (SDLC & Design) · COA 2 (Digital Logic) · AI/Data 2 (AI/ML Basics) · Web 1 (HTML & CSS) · Cloud 1 (Cloud Models)" }, quant: { item: "DI sets (5 Q each): Table DI, Bar DI, Line DI 5 each: Series (missing), Quantity Comparison, Simplification Arithmetic 10 (2 each): Percentage, Ratio & Proportion, Profit & Loss, Simple Interest, CI & Instalments" }, reasoning: { item: "Puzzles (5 Q each): Linear (same facing), Floor Puzzle, Month-Date Puzzle, Circular (centre) 5 each: Syllogism (basic), Direct Inequality, Blood Rel. (verbal), Coding (shifting)" }, english: { item: "RC 10: RC Factual (rural credit and RRBs) 5 each: Cloze (grammar), ED: SVA & Tenses, Double Fillers, Para Jumbles (5), Phrase Replacement, Word Usage/Swap" } },
    { day: 65, date: "2026-12-01", label: "Tue 01 Dec", test: "Full Mock 02", pattern: "Pattern B · 160 Q · 120 min", pk: { plan: "DBMS 5 (SQL & RA) · CN 5 (Data Link) · Sec 4 (Cryptography) · DSA 4 (Trees & Hashing) · OS 3 (Sync & Deadlock) · Python 3 (Py Data Structures) · Java 2 (Java Advanced) · C 1 (C Pointers & Functions) · C++ 1 (C++ Advanced) · SE 2 (Testing & Estimation) · COA 2 (CPU, Cache & Pipeline) · AI/Data 2 (DW, Mining & BI) · Web 2 (JS, HTTP & REST) · Cloud 2 (Virtualization) · Web3 1 (Blockchain/Web3/IoT) · Bank IT 1 (Banking IT)" }, quant: { item: "DI sets (5 Q each): Pie DI, Caselet DI, Missing-value DI 5 each: Series (wrong), Data Sufficiency, Approximation Arithmetic 10 (2 each): Time & Work, Speed-Time-Distance, Averages, Ages, Mixture & Alligation" }, reasoning: { item: "Puzzles (5 Q each): Box Puzzle, Year/Age Puzzle, Parallel-row, Floor-Flat Puzzle 5 each: Syllogism (only a few), Direct Inequality, Direction (point), Order & Ranking" }, english: { item: "RC 10: RC Inference (UPI and digital payments) 5 each: Cloze (vocab), ED: Articles/Preps, Triple Fillers, Para Jumbles (fixed), Connectors, Idioms/Phrasal" } },
    { day: 66, date: "2026-12-02", label: "Wed 02 Dec", test: "Full Mock 03", pattern: "Pattern B · 160 Q · 120 min", pk: { plan: "DBMS 5 (Normalization) · CN 5 (IP & Routing) · Sec 5 (Network Security) · DSA 4 (Graphs & Sorting) · OS 4 (Memory & VM) · Python 3 (Py OOP & Libraries) · Java 2 (Java Core) · C 2 (C Basics) · C++ 2 (OOP in C++) · SE 2 (SDLC & Design) · COA 2 (Digital Logic) · AI/Data 2 (AI/ML Basics) · Web 1 (HTML & CSS) · Cloud 1 (Cloud Models)" }, quant: { item: "DI sets (5 Q each): Bar+Line DI, Pie+Table DI, Stacked Bar DI 5 each: Series (new pattern), Quadratic Eq., Simplification Arithmetic 10 (2 each): Trains, Boats & Streams, Pipes & Cisterns, Partnership, Discount & MP" }, reasoning: { item: "Puzzles (5 Q each): Designation Puzzle, Circular (mixed), Comparison Puzzle, Day Scheduling 5 each: Syllogism (basic), Coded Inequality, Input-Output, Assumption" }, english: { item: "RC 10: RC Main Idea (cybersecurity in banks) 5 each: Cloze (error-based), ED: Pronouns/Modifiers, Common-word Fillers, Para Jumbles (6), Odd Sentence/Para Compl., Column-based" } },
    { day: 67, date: "2026-12-03", label: "Thu 03 Dec", test: "Review 1", pattern: "Mocks 01-03 · ~2 h", pk: { plan: "Re-attempt every wrong and skipped question from Mocks 01-03 without looking at solutions, then check. Tag each by cause (concept / calculation / misread / time). Fix the three causes that repeat most: re-read notes only for those. PK: which area lost the most marks against its weight? No new questions today." } },
    { day: 68, date: "2026-12-04", label: "Fri 04 Dec", test: "Full Mock 04", pattern: "Pattern B · 160 Q · 120 min", pk: { plan: "DBMS 5 (Transactions) · CN 5 (Transport) · Sec 4 (Attacks & AppSec) · DSA 4 (Algorithm Design) · OS 3 (Files, Disk & Linux) · Python 3 (Python Basics) · Java 2 (Java Advanced) · C 1 (C Pointers & Functions) · C++ 1 (C++ Advanced) · SE 2 (Testing & Estimation) · COA 2 (CPU, Cache & Pipeline) · AI/Data 2 (DW, Mining & BI) · Web 2 (JS, HTTP & REST) · Cloud 2 (Virtualization) · Web3 1 (Blockchain/Web3/IoT) · Bank IT 1 (Banking IT)" }, quant: { item: "DI sets (5 Q each): Arithmetic DI, Double Pie DI, Growth-rate DI 5 each: Series (missing), Quantity Comparison, Approximation Arithmetic 10 (2 each): Mensuration 2D, Mensuration 3D, P&C, Probability, Number System" }, reasoning: { item: "Puzzles (5 Q each): Square/Rect Seating, Uncertain-number, Linear (mixed facing), Box (multi-attr) 5 each: Syllogism (only a few), Coded Inequality, Alphanumeric Series, Blood Rel. (coded)" }, english: { item: "RC 10: RC Vocab-in-context (AI and jobs) 5 each: Cloze (grammar), ED: Nouns/Quantifiers, Fixed Fillers, Para Jumbles (5), Word Rearrangement, Sentence Parts Rearr." } },
    { day: 69, date: "2026-12-05", label: "Sat 05 Dec", test: "Full Mock 05", pattern: "Pattern B · 160 Q · 120 min", pk: { plan: "DBMS 5 (Indexing & Recovery) · CN 5 (App Protocols) · Sec 5 (Sec. Mgmt & Banking) · DSA 4 (Linear DS) · OS 4 (Processes & Scheduling) · Python 3 (Py Data Structures) · Java 2 (Java Core) · C 2 (C Basics) · C++ 2 (OOP in C++) · SE 2 (SDLC & Design) · COA 2 (Digital Logic) · AI/Data 2 (AI/ML Basics) · Web 1 (HTML & CSS) · Cloud 1 (Cloud Models)" }, quant: { item: "DI sets (5 Q each): Arithmetic Caselet, Radar DI †, Table DI 5 each: Series (wrong), Data Sufficiency, Simplification Arithmetic 10 (2 each): Linear Equations, Percentage, Ratio & Proportion, Profit & Loss, Simple Interest" }, reasoning: { item: "Puzzles (5 Q each): Double-attribute, Unknown-number Seating, Family-tree Puzzle, Linear (distance) 5 each: Syllogism (basic), Direct Inequality, Coding (sentence), Data Sufficiency" }, english: { item: "RC 10: RC Tone & Purpose (climate risk and agriculture) 5 each: Cloze (vocab), ED: Inversion/Comparison, Sentence Completion, Para Jumbles (fixed), Misspelt Words, Starters/Combining" } },
    { day: 70, date: "2026-12-06", label: "Sun 06 Dec", test: "Full Mock 06", pattern: "Pattern B · 160 Q · 120 min", pk: { plan: "DBMS 5 (ER & Keys) · CN 5 (Models & Devices) · Sec 4 (Fundamentals & Malware) · DSA 4 (Trees & Hashing) · OS 3 (Sync & Deadlock) · Python 3 (Py OOP & Libraries) · Java 2 (Java Advanced) · C 1 (C Pointers & Functions) · C++ 1 (C++ Advanced) · SE 2 (Testing & Estimation) · COA 2 (CPU, Cache & Pipeline) · AI/Data 2 (DW, Mining & BI) · Web 2 (JS, HTTP & REST) · Cloud 2 (Virtualization) · Web3 1 (Blockchain/Web3/IoT) · Bank IT 1 (Banking IT)" }, quant: { item: "DI sets (5 Q each): Bar DI, Line DI, Pie DI 5 each: Series (new pattern), Quadratic Eq., Approximation Arithmetic 10 (2 each): CI & Instalments, Time & Work, Speed-Time-Distance, Averages, Ages" }, reasoning: { item: "Puzzles (5 Q each): Direction Puzzle, Linear (same facing), Floor Puzzle, Month-Date Puzzle 5 each: Syllogism (only a few), Direct Inequality, Direction (coded), Conclusion" }, english: { item: "RC 10: RC Short Passages (monetary policy and inflation) 5 each: Cloze (error-based), ED: Conditionals/Modals, Single Fillers, Para Jumbles (6), Paragraph Summary, Confused Words" } },
    { day: 71, date: "2026-12-07", label: "Mon 07 Dec", test: "Review 2", pattern: "Mocks 04-06 · ~2 h", pk: { plan: "Re-attempt every wrong and skipped question from Mocks 04-06 without looking at solutions, then check. Tag each by cause (concept / calculation / misread / time). Fix the three causes that repeat most: re-read notes only for those. PK: which area lost the most marks against its weight? No new questions today." } },
    { day: 72, date: "2026-12-08", label: "Tue 08 Dec", test: "Full Mock 07", pattern: "Pattern B · 160 Q · 120 min", pk: { plan: "DBMS 5 (SQL & RA) · CN 5 (Data Link) · Sec 5 (Cryptography) · DSA 4 (Graphs & Sorting) · OS 4 (Memory & VM) · Python 3 (Python Basics) · Java 2 (Java Core) · C 2 (C Basics) · C++ 2 (OOP in C++) · SE 2 (SDLC & Design) · COA 2 (Digital Logic) · AI/Data 2 (AI/ML Basics) · Web 1 (HTML & CSS) · Cloud 1 (Cloud Models)" }, quant: { item: "DI sets (5 Q each): Caselet DI, Missing-value DI, Bar+Line DI 5 each: Series (missing), Quantity Comparison, Simplification Arithmetic 10 (2 each): Mixture & Alligation, Trains, Boats & Streams, Pipes & Cisterns, Partnership" }, reasoning: { item: "Puzzles (5 Q each): Circular (centre), Box Puzzle, Year/Age Puzzle, Parallel-row 5 each: Syllogism (basic), Coded Inequality, Alphabet & Word, Number-based" }, english: { item: "RC 10: RC Statement Eval. (financial inclusion) 5 each: Cloze (grammar), Correct Sentence, Double Fillers, Para Jumbles (5), Collocations, Synonyms/Antonyms †" } },
    { day: 73, date: "2026-12-09", label: "Wed 09 Dec", test: "Full Mock 08", pattern: "Pattern B · 160 Q · 120 min", pk: { plan: "DBMS 5 (Normalization) · CN 5 (IP & Routing) · Sec 4 (Network Security) · DSA 4 (Algorithm Design) · OS 3 (Files, Disk & Linux) · Python 3 (Py Data Structures) · Java 2 (Java Advanced) · C 1 (C Pointers & Functions) · C++ 1 (C++ Advanced) · SE 2 (Testing & Estimation) · COA 2 (CPU, Cache & Pipeline) · AI/Data 2 (DW, Mining & BI) · Web 2 (JS, HTTP & REST) · Cloud 2 (Virtualization) · Web3 1 (Blockchain/Web3/IoT) · Bank IT 1 (Banking IT)" }, quant: { item: "DI sets (5 Q each): Pie+Table DI, Stacked Bar DI, Arithmetic DI 5 each: Series (wrong), Data Sufficiency, Approximation Arithmetic 10 (2 each): Discount & MP, Mensuration 2D, Mensuration 3D, P&C, Probability" }, reasoning: { item: "Puzzles (5 Q each): Floor-Flat Puzzle, Designation Puzzle, Circular (mixed), Comparison Puzzle 5 each: Syllogism (only a few), Coded Inequality, Course of Action, Coding (new pattern)" }, english: { item: "RC 10: RC Critical Reading (data privacy) 5 each: Cloze (vocab), Bold-word Errors, Triple Fillers, Para Jumbles (fixed), One-word Subst. †, Phrase Replacement" } },
    { day: 74, date: "2026-12-10", label: "Thu 10 Dec", test: "Full Mock 09", pattern: "Pattern B · 160 Q · 120 min", pk: { plan: "DBMS 5 (Transactions) · CN 5 (Transport) · Sec 5 (Attacks & AppSec) · DSA 4 (Linear DS) · OS 4 (Processes & Scheduling) · Python 3 (Py OOP & Libraries) · Java 2 (Java Core) · C 2 (C Basics) · C++ 2 (OOP in C++) · SE 2 (SDLC & Design) · COA 2 (Digital Logic) · AI/Data 2 (AI/ML Basics) · Web 1 (HTML & CSS) · Cloud 1 (Cloud Models)" }, quant: { item: "DI sets (5 Q each): Double Pie DI, Growth-rate DI, Arithmetic Caselet 5 each: Series (new pattern), Quadratic Eq., Simplification Arithmetic 10 (2 each): Number System, Linear Equations, Percentage, Ratio & Proportion, Profit & Loss" }, reasoning: { item: "Puzzles (5 Q each): Day Scheduling, Square/Rect Seating, Uncertain-number, Linear (mixed facing) 5 each: Syllogism (basic), Direct Inequality, Strengthen/Weaken, Cause-Effect/Inference" }, english: { item: "RC 10: RC Long Passage (global trade and tariffs) 5 each: Cloze (error-based), ED: SVA & Tenses, Common-word Fillers, Para Jumbles (6), Word Usage/Swap, Connectors" } },
    { day: 75, date: "2026-12-11", label: "Fri 11 Dec", test: "Review 3", pattern: "Mocks 07-09 · ~2 h", pk: { plan: "Re-attempt every wrong and skipped question from Mocks 07-09 without looking at solutions, then check. Tag each by cause (concept / calculation / misread / time). Fix the three causes that repeat most: re-read notes only for those. PK: which area lost the most marks against its weight? No new questions today." } },
    { day: 76, date: "2026-12-12", label: "Sat 12 Dec", test: "Full Mock 10", pattern: "Pattern B · 160 Q · 120 min", pk: { plan: "DBMS 5 (Indexing & Recovery) · CN 5 (App Protocols) · Sec 4 (Sec. Mgmt & Banking) · DSA 4 (Trees & Hashing) · OS 3 (Sync & Deadlock) · Python 3 (Python Basics) · Java 2 (Java Advanced) · C 1 (C Pointers & Functions) · C++ 1 (C++ Advanced) · SE 2 (Testing & Estimation) · COA 2 (CPU, Cache & Pipeline) · AI/Data 2 (DW, Mining & BI) · Web 2 (JS, HTTP & REST) · Cloud 2 (Virtualization) · Web3 1 (Blockchain/Web3/IoT) · Bank IT 1 (Banking IT)" }, quant: { item: "DI sets (5 Q each): Radar DI †, Table DI, Bar DI 5 each: Series (missing), Quantity Comparison, Approximation Arithmetic 10 (2 each): Simple Interest, CI & Instalments, Time & Work, Speed-Time-Distance, Averages" }, reasoning: { item: "Puzzles (5 Q each): Box (multi-attr), Double-attribute, Unknown-number Seating, Family-tree Puzzle 5 each: Syllogism (only a few), Direct Inequality, Miscellaneous, Blood Rel. (verbal)" }, english: { item: "RC 10: RC Factual (renewable energy transition) 5 each: Cloze (grammar), ED: Articles/Preps, Fixed Fillers, Para Jumbles (5), Idioms/Phrasal, Odd Sentence/Para Compl." } },
    { day: 77, date: "2026-12-13", label: "Sun 13 Dec", test: "Full Mock 11", pattern: "Pattern B · 160 Q · 120 min", pk: { plan: "DBMS 5 (ER & Keys) · CN 5 (Models & Devices) · Sec 5 (Fundamentals & Malware) · DSA 4 (Graphs & Sorting) · OS 4 (Memory & VM) · Python 3 (Py Data Structures) · Java 2 (Java Core) · C 2 (C Basics) · C++ 2 (OOP in C++) · SE 2 (SDLC & Design) · COA 2 (Digital Logic) · AI/Data 2 (AI/ML Basics) · Web 1 (HTML & CSS) · Cloud 1 (Cloud Models)" }, quant: { item: "DI sets (5 Q each): Line DI, Pie DI, Caselet DI 5 each: Series (wrong), Data Sufficiency, Simplification Arithmetic 10 (2 each): Ages, Mixture & Alligation, Trains, Boats & Streams, Pipes & Cisterns" }, reasoning: { item: "Puzzles (5 Q each): Linear (distance), Direction Puzzle, Linear (same facing), Floor Puzzle 5 each: Syllogism (basic), Coded Inequality, Coding (shifting), Direction (point)" }, english: { item: "RC 10: RC Inference (public health systems) 5 each: Cloze (vocab), ED: Pronouns/Modifiers, Sentence Completion, Para Jumbles (fixed), Column-based, Word Rearrangement" } },
    { day: 78, date: "2026-12-14", label: "Mon 14 Dec", test: "Full Mock 12", pattern: "Pattern B · 160 Q · 120 min", pk: { plan: "DBMS 5 (SQL & RA) · CN 5 (Data Link) · Sec 4 (Cryptography) · DSA 4 (Algorithm Design) · OS 3 (Files, Disk & Linux) · Python 3 (Py OOP & Libraries) · Java 2 (Java Advanced) · C 1 (C Pointers & Functions) · C++ 1 (C++ Advanced) · SE 2 (Testing & Estimation) · COA 2 (CPU, Cache & Pipeline) · AI/Data 2 (DW, Mining & BI) · Web 2 (JS, HTTP & REST) · Cloud 2 (Virtualization) · Web3 1 (Blockchain/Web3/IoT) · Bank IT 1 (Banking IT)" }, quant: { item: "DI sets (5 Q each): Missing-value DI, Bar+Line DI, Pie+Table DI 5 each: Series (new pattern), Quadratic Eq., Approximation Arithmetic 10 (2 each): Partnership, Discount & MP, Mensuration 2D, Mensuration 3D, P&C" }, reasoning: { item: "Puzzles (5 Q each): Month-Date Puzzle, Circular (centre), Box Puzzle, Year/Age Puzzle 5 each: Syllogism (only a few), Coded Inequality, Order & Ranking, Input-Output" }, english: { item: "RC 10: RC Main Idea (fintech regulation) 5 each: Cloze (error-based), ED: Nouns/Quantifiers, Single Fillers, Para Jumbles (6), Sentence Parts Rearr., Misspelt Words" } },
    { day: 79, date: "2026-12-15", label: "Tue 15 Dec", test: "Review 4", pattern: "Mocks 10-12 · ~2 h", pk: { plan: "Re-attempt every wrong and skipped question from Mocks 10-12 without looking at solutions, then check. Tag each by cause (concept / calculation / misread / time). Fix the three causes that repeat most: re-read notes only for those. PK: which area lost the most marks against its weight? No new questions today." } },
    { day: 80, date: "2026-12-16", label: "Wed 16 Dec", test: "Full Mock 13", pattern: "Pattern B · 160 Q · 120 min", pk: { plan: "DBMS 5 (Normalization) · CN 5 (IP & Routing) · Sec 5 (Network Security) · DSA 4 (Linear DS) · OS 4 (Processes & Scheduling) · Python 3 (Python Basics) · Java 2 (Java Core) · C 2 (C Basics) · C++ 2 (OOP in C++) · SE 2 (SDLC & Design) · COA 2 (Digital Logic) · AI/Data 2 (AI/ML Basics) · Web 1 (HTML & CSS) · Cloud 1 (Cloud Models)" }, quant: { item: "DI sets (5 Q each): Stacked Bar DI, Arithmetic DI, Double Pie DI 5 each: Series (missing), Quantity Comparison, Simplification Arithmetic 10 (2 each): Probability, Number System, Linear Equations, Percentage, Ratio & Proportion" }, reasoning: { item: "Puzzles (5 Q each): Parallel-row, Floor-Flat Puzzle, Designation Puzzle, Circular (mixed) 5 each: Syllogism (basic), Direct Inequality, Assumption, Alphanumeric Series" }, english: { item: "RC 10: RC Vocab-in-context (behavioural economics) 5 each: Cloze (grammar), ED: Inversion/Comparison, Double Fillers, Para Jumbles (5), Starters/Combining, Paragraph Summary" } },
    { day: 81, date: "2026-12-17", label: "Thu 17 Dec", test: "Full Mock 14", pattern: "Pattern B · 160 Q · 120 min", pk: { plan: "DBMS 5 (Transactions) · CN 5 (Transport) · Sec 4 (Attacks & AppSec) · DSA 4 (Trees & Hashing) · OS 3 (Sync & Deadlock) · Python 3 (Py Data Structures) · Java 2 (Java Advanced) · C 1 (C Pointers & Functions) · C++ 1 (C++ Advanced) · SE 2 (Testing & Estimation) · COA 2 (CPU, Cache & Pipeline) · AI/Data 2 (DW, Mining & BI) · Web 2 (JS, HTTP & REST) · Cloud 2 (Virtualization) · Web3 1 (Blockchain/Web3/IoT) · Bank IT 1 (Banking IT)" }, quant: { item: "DI sets (5 Q each): Growth-rate DI, Arithmetic Caselet, Radar DI † 5 each: Series (wrong), Data Sufficiency, Approximation Arithmetic 10 (2 each): Profit & Loss, Simple Interest, CI & Instalments, Time & Work, Races & Circular †" }, reasoning: { item: "Puzzles (5 Q each): Comparison Puzzle, Day Scheduling, Square/Rect Seating, Uncertain-number 5 each: Syllogism (only a few), Direct Inequality, Blood Rel. (coded), Coding (sentence)" }, english: { item: "RC 10: RC Tone & Purpose (MSME credit) 5 each: Cloze (vocab), ED: Conditionals/Modals, Triple Fillers, Para Jumbles (fixed), Confused Words, Collocations" } },
    { day: 82, date: "2026-12-18", label: "Fri 18 Dec", test: "Full Mock 15", pattern: "Pattern B · 160 Q · 120 min", pk: { plan: "DBMS 5 (Indexing & Recovery) · CN 5 (App Protocols) · Sec 5 (Sec. Mgmt & Banking) · DSA 4 (Graphs & Sorting) · OS 4 (Memory & VM) · Python 3 (Py OOP & Libraries) · Java 2 (Java Core) · C 2 (C Basics) · C++ 2 (OOP in C++) · SE 2 (SDLC & Design) · COA 2 (Digital Logic) · AI/Data 2 (AI/ML Basics) · Web 1 (HTML & CSS) · Cloud 1 (Cloud Models)" }, quant: { item: "DI sets (5 Q each): Table DI, Bar DI, Line DI 5 each: Series (new pattern), Quadratic Eq., Simplification Arithmetic 10 (2 each): Averages, Ages, Mixture & Alligation, Trains, Boats & Streams" }, reasoning: { item: "Puzzles (5 Q each): Linear (mixed facing), Box (multi-attr), Double-attribute, Unknown-number Seating 5 each: Syllogism (basic), Coded Inequality, Data Sufficiency, Direction (coded)" }, english: { item: "RC 10: RC Short Passages (open banking and APIs) 5 each: Cloze (error-based), Correct Sentence, Common-word Fillers, Para Jumbles (6), Synonyms/Antonyms †, One-word Subst. †" } },
    { day: 83, date: "2026-12-19", label: "Sat 19 Dec", test: "Final light day", pattern: "No mock", pk: { plan: "Morning: re-attempt Mock 13-15 errors. Afternoon: formula sheet and PK one-pagers (subnetting, scheduling, EMAT/AMAT, cache mapping, COCOMO numericals; C/Java/Python output-question traps). Stop by evening; check call letter, ID, route, reporting time." } },
    { day: 84, date: "2026-12-20", label: "Sun 20 Dec", test: "EXAM", pk: { topic: "IBPS RRB Officer Scale II single online exam", plan: "IBPS calendar date; tentative - your call letter has the final date, shift and reporting time." } },
    ],
  },
]

/** Every day, flat, in order. The sections are how it is read, not how it is stored. */
export const SCHEDULE_DAYS: ScheduleDay[] = SCHEDULE.flatMap((s) => s.days)

export const SCHEDULE_FIRST = SCHEDULE_DAYS[0]!.date
export const SCHEDULE_LAST = SCHEDULE_DAYS[SCHEDULE_DAYS.length - 1]!.date

/**
 * The day the plan puts on this date, or null if the date is outside it.
 *
 * Takes an IST date string because that is what every other date in this
 * application is; converting a clock to one is `istToday`'s job, not this.
 */
export function scheduleDayOn(date: string): ScheduleDay | null {
  return SCHEDULE_DAYS.find((d) => d.date === date) ?? null
}

/** The section a day belongs to. */
export function sectionOf(day: ScheduleDay): ScheduleSection {
  return SCHEDULE.find((s) => s.days.includes(day)) ?? SCHEDULE[0]!
}

/**
 * The next day on or after this date, for a date the plan has not reached yet.
 * Null once the plan is behind you.
 */
export function nextScheduleDay(date: string): ScheduleDay | null {
  return SCHEDULE_DAYS.find((d) => d.date >= date) ?? null
}

/**
 * How many days carry each pattern, which is the legend the PDF put on a cover
 * page this file does not have. Counted rather than written down, so it cannot
 * drift from the table underneath it.
 */
export function schedulePatterns(): { pattern: string; days: number }[] {
  const counts = new Map<string, number>()
  for (const d of SCHEDULE_DAYS) {
    if (!d.pattern?.startsWith('Pattern ')) continue
    counts.set(d.pattern, (counts.get(d.pattern) ?? 0) + 1)
  }
  return [...counts].sort().map(([pattern, days]) => ({ pattern, days }))
}
